name: pragmatic_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  url_launcher: ^6.2.5
  provider: ^6.1.2
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.3.2

  drift: ^2.17.0
  drift_flutter: any
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.2
  path: ^1.9.0

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  test: ^1.25.2
  build_runner: ^2.4.6
  drift_dev: ^2.17.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/app_logo.png"
  image_path_android: "assets/launcher/app_logo.png"
  adaptive_icon_background: "assets/launcher/app_logo_background.png"
  adaptive_icon_foreground: "assets/launcher/app_logo.png"
